/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

/**
 *
 * @author Diana Paola
 */
public class VistaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VistaPrincipal
     */
    JFileChooser openFile;
    File f;
    String textComplete="";
    String fileName;
    
            
    public VistaPrincipal() {
        initComponents();
    }
    
    public void helloWorld(){
        System.out.println("Hola mundo :3 ");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboOptions = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentFile = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LabelFileName = new javax.swing.JLabel();
        LabelPrivateKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newFileContent = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encrypt", "Decrypt" }));
        comboOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOptionsActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("File...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        contentFile.setColumns(20);
        contentFile.setRows(5);
        jScrollPane1.setViewportView(contentFile);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Content file");

        LabelFileName.setText("File name");

        LabelPrivateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelPrivateKeyActionPerformed(evt);
            }
        });

        jLabel2.setText("Insert secret key");

        jLabel3.setText("Choose an option");

        newFileContent.setColumns(20);
        newFileContent.setRows(5);
        jScrollPane2.setViewportView(newFileContent);

        jLabel4.setText("File encrypted");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(LabelFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(LabelPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFileName)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabelFileName.getAccessibleContext().setAccessibleName("FileName");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOptionsActionPerformed
        int option = comboOptions.getSelectedIndex();
        
        String claveEncriptation = LabelPrivateKey.getText();
        String datosOriginales =  textComplete;
        
        String ruta = f.getParent();
        //System.out.println("RUTA: " + ruta); 
        int dotIndex = fileName.lastIndexOf('.');
        fileName = fileName.substring(0, dotIndex);

        contentFile.setText(datosOriginales);
        AESFunction encriptador = new AESFunction();
        
        if(option == 0){
            LabelFileName.setText("option 0");
            
            try {        
                String msgCifrado = encriptador.cifrar(datosOriginales, claveEncriptation);
                
                try{
                    ruta += "\\" + fileName + "_C" + ".txt";
                    FileWriter newFile= new FileWriter(ruta);
                    
                    newFile.write(msgCifrado);
                    newFile.close();
                }catch(IOException e){
                    System.out.println("An error occurred.");
                    e.printStackTrace();   
                }

                //System.out.println("Cadena Original: " + datosOriginales);
                //System.out.println("Escriptado     : " + encriptado);
                newFileContent.setText(msgCifrado);          

            } catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                Logger.getLogger(AESFunction.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else if(option == 1){
            LabelFileName.setText("optiion 1");
            try{
                String msgDescifrado = encriptador.descifrar(datosOriginales, claveEncriptation);
                try{
                    ruta += "\\" + fileName + "_D" + ".txt";
                    FileWriter newFile= new FileWriter(ruta);
                    newFile.write(msgDescifrado);
                    newFile.close();
                    newFileContent.setText(msgDescifrado);
                }catch(IOException e){
                    System.out.println("An error occurred.");
                    e.printStackTrace();   
                }
            }catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                Logger.getLogger(AESFunction.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_comboOptionsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        helloWorld();
        openFile = new JFileChooser();
        int r = openFile.showOpenDialog(null);
        
        if(r==JFileChooser.APPROVE_OPTION){
            f = openFile.getSelectedFile();
            fileName = f.getName();
            String path = f.getAbsolutePath();
            LabelFileName.setText(fileName);

           try {
                Scanner scanner = new Scanner(new File(path));
                textComplete = scanner.nextLine();
                textComplete += "\n";
                //contentFile.setText(scanner.nextLine());
                //contentFile.setText(textComplete);
                while(scanner.hasNextLine()) {
                    textComplete += scanner.nextLine();
                    textComplete += "\n";
                    //contentFile.setText(textComplete);
                    //contentFile.setText(contentFile.getText() + "\n" + scanner.nextLine());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LabelPrivateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelPrivateKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelPrivateKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFileName;
    private javax.swing.JTextField LabelPrivateKey;
    private javax.swing.JComboBox<String> comboOptions;
    private javax.swing.JTextArea contentFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea newFileContent;
    // End of variables declaration//GEN-END:variables
}
